node_specs:
  - extension: pem
    icon: key
  - extension: pdf
    icon: pdf
  - extension: sh
    icon: sh
nerd_icons:
  key: "\uf084"
  pdf: "\uf411"
  share: "\uf14d"
  link:  "\ue370"
  sh:    "\uf489"
emoji_icons:
  key: "🔑"
  pdf: "📄"
  share: "🎁"
  link: "🔗"
  sh:   "🐚"
constants:
  node_types:
    symlink:
      icon: link
      color: bright_magenta
